config/routes.rb
Rails.application.routes.draw do

  devise_for :users,
    path: '',
    path_names: {sign_in: 'login', sign_out: 'logout'},
    controllers: { omniauth_callbacks: 'omniauth_callbacks' }

   root 'dashboards#index'

  resources :dashboards, only: [:index]

  get 'profile', to: 'profiles#show', as: :profile
  get 'profile/edit', to: 'profiles#edit', as: :edit_profile
  put 'profile', to: 'profiles#update'
  get 'profile/edit_password', to: 'profiles#edit_password', as: :edit_password_profile

  resources :activities

  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  get "messages/inbox" => "messages#inbox", as: :messages_inbox
  get "messages/sent" => "messages#sent", as: :messages_sent
  get "messages/trash" => "messages#trash", as: :messages_trash

  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

  resources :people, only: [:index, :show] do
    member do
      post :follow
      post :unfollow
    end
  end

end

app/controllers/conversations_controller.rb
class ConversationsController < BaseController
  @@use_resource = false
  before_filter :receipts, only: [:show]

  def new
  end

  def create
    create_mailboxer
    if @mailboxer.valid?
      respond_to do |f|
        f.html{ redirect_to conversation_path @mailboxer.conversation, success: "Your message was successfully sent!" }
        f.js{}
      end
    else
      respond_to do |f|
        f.html{ render :new }
        f.js{}
      end
    end
  end

  def show
    conversation.mark_as_read(current_user)
  end

  def reply
    reply_conversation
    if @mailboxer.valid?
      respond_to do |f|
        f.html {redirect_to conversation_path conversation, notice: "Your reply message was successfully sent!"}
      end
    else
      respond_to do |f|
        receipts
        f.html{render :show}
      end
    end
  end

  def trash
    conversation.move_to_trash(current_user)
    redirect_to messages_inbox_path
  end

  def untrash
    conversation.untrash(current_user)
    redirect_to messages_inbox_path
  end

  private

  def conversation_params
    params.require(:conversation).permit(:subject, :body,recipients:[])
  end

  def message_params
    params.require(:message).permit(:body, :subject)
  end

  def reply_subject
    message_params[:subject]
  end

  def recipients
    @recipients ||= User.where(id: conversation_params[:recipients])
  end

  def create_mailboxer
    @mailboxer ||= current_user.send_message(recipients, conversation_params[:body], conversation_params[:subject])
  end

  def receipts
    @receipts = conversation.receipts_for(current_user)
  end

  def reply_conversation
    @mailboxer ||= current_user.reply_to_conversation conversation, message_params[:body], reply_subject
  end

end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/_conversation.html.erb
<div class="media">
  <div class="media-left">
    <a href="#">
      <%= image_tag avatar, class: 'media-object update-card-MDimentions', width: 64, height: 64 %>
    </a>
  </div>
  <div class="media-body">
    <h4 class="media-heading">
      <%= conversation.originator.name %> <br>
      <small><b>Subject: </b><%= conversation.subject %></small><br>
      <small><b>Date: </b><%=  conversation.messages.last.created_at.strftime("%A, %b %d, %Y at %I:%M%p") %></small>
    </h4>
    <%= truncate conversation.messages.last.body, length: 145 %>
    <%= link_to "View", conversation_path(conversation)  %>
  </div>
</div>

app/views/conversations/_form.html.erb
<%= render partial: 'shared/errors_explanation', locals: {errors: @mailboxer.errors } unless @mailboxer.nil? %>
<%= form_for :conversation, url: :conversations, html: { class: "form form-horizontal" } do |f| %>
    <div class="form-group">
      <%= f.label :recipients %>
      <%= f.select(:recipients, User.all.collect {|p| [ p.name, p.id ] }, {}, { multiple: true , class: "form-control" })%>
    </div>
    <div class="form-group">
      <%= f.label :subject %>
      <%= f.text_field :subject, placeholder: "Subject", class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :message %>
      <%= f.text_area :body, class: 'form-control',placeholder: "Type your message here", rows: 4  %>
    </div>

    <%= f.submit "Send Message", class: "btn btn-success" %>

<% end %>

app/views/conversations/_form_reply.html.erb
<%= render partial: 'shared/errors_explanation', locals: {errors: @mailboxer.errors } unless @mailboxer.nil? %>

<%= form_for :message, url: reply_conversation_path(conversation) do |f| %>
    <div class="form-group">
      <%= f.text_field :subject, placeholder: "Subject Reply", class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.text_area :body, placeholder: "Reply Message", rows: 4, class: "form-control" %>
    </div>
    <%= f.submit "Reply", class: 'btn btn-danger pull-right' %>
<% end %>

app/views/conversations/_messages.html.erb
<% receipts.each do |receipt| %>
    <% message = receipt.message %>
    <div class="media">
      <div class="media-left">
        <a href="#">
          <%= image_tag avatar, class: 'media-object update-card-MDimentions', width: 64, height: 64 %>
        </a>
      </div>
      <div class="media-body">
        <h4 class="media-heading">
          <%= message.sender.name %> <br>
          <small><b>Subject: </b><%= message.subject %></small><br>
          <small><b>Date: </b><%=  message.created_at.strftime("%A, %b %d, %Y at %I:%M%p") %></small>
        </h4>
        <%= message.body %>
      </div>
    </div>
<% end %>

app/views/conversations/new.html.erb
<%= render partial: 'messages/messages_folder', locals: { is_conversation: true } %>

app/views/conversations/show.html.erb
<div class="row">
  <div class="spacer"></div>
   <div class="col-md-6">
    <%= link_to "Compose", new_conversation_path, class: "btn btn-success" %>
  </div>
  <div class="col-md-6 text-right">
    <% if conversation.is_trashed?(current_user) %>
        <%= link_to 'Untrash', untrash_conversation_path(conversation), class: 'btn btn-info', method: :post %>
    <% else %>
        <%= link_to 'Move to trash', trash_conversation_path(conversation), class: 'btn btn-danger', method: :post,
                    data: {confirm: 'Are you sure?'} %>
    <% end %>
  </div>

  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= render 'messages/messages_folder_nav' %>
      </div>
    </div>
  </div>

  <div class="col-md-8">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= render partial: 'messages', locals: {receipts: @receipts} %>
      </div>
      <div class="panel-footer">
          <%= render partial: 'form_reply' %>
        <div class="clearfix"></div>
      </div>
    </div>
  </div>

</div>