config/routes.rb
Rails.application.routes.draw do

  devise_for :users,
    path: '',
    path_names: {sign_in: 'login', sign_out: 'logout'},
    controllers: { omniauth_callbacks: 'omniauth_callbacks' }

   root 'dashboards#index'

  resources :dashboards, only: [:index]

  get 'profile', to: 'profiles#show', as: :profile
  get 'profile/edit', to: 'profiles#edit', as: :edit_profile
  put 'profile', to: 'profiles#update'
  get 'profile/edit_password', to: 'profiles#edit_password', as: :edit_password_profile

  resources :activities

  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  get "messages/inbox" => "messages#inbox", as: :messages_inbox
  get "messages/sent" => "messages#sent", as: :messages_sent
  get "messages/trash" => "messages#trash", as: :messages_trash

  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

  resources :people, only: [:index, :show] do
    member do
      post :follow
      post :unfollow
    end
  end

end

app/models/activity.rb
class Activity < ActiveRecord::Base

  extend FriendlyId

  belongs_to :user
  has_one :link
  has_one :photo
  has_one :post
  has_many :manifests
  has_many :identities, through: :manifests
  accepts_nested_attributes_for :manifests

  friendly_id :title, :use => :slugged

  validates_presence_of :title

  before_save :content

  attr_accessor :image, :image_description, :video, :video_description, :status

  validate :share

  class << self
  end

  def create_activity
    manifests.each do |manifest| manifests.delete(manifest) unless manifest.publish_on end
    save
  end

  def image?
    image.instance_of? ActionDispatch::Http::UploadedFile
  end

  def link?
    /(https?:\/\/)?\w*\.\w+(\.\w+)*(\/\w+)*(\.\w*)?/.match(title)
  end

  def content
    begin
      if image?
        build_photo name: image
      elsif link?
        url = link?.to_s
        build_link(url: url)
      else
        build_post content: title
      end
    rescue e
      return false
    end
  end

  def share

  end

end

app/models/follow.rb
class Follow < Socialization::ActiveRecordStores::Follow
end

app/models/identity.rb
class Identity < ActiveRecord::Base
  belongs_to :user
  has_many :manifests
  has_many :activities, through: :manifests
  accepts_nested_attributes_for :manifests

  validates_presence_of :uid, :provider
  validates_uniqueness_of :uid, :scope => :provider

  class << self
	  def find_for_oauth(auth)
	    find_or_create_by(uid: auth.uid, provider: auth.provider)
	  end
  end
end

app/models/like.rb
class Like < Socialization::ActiveRecordStores::Like
end

app/models/link.rb
class Link < ActiveRecord::Base

  belongs_to :activity

  validates :url, presence: true
end

app/models/manifest.rb
class Manifest < ActiveRecord::Base
  belongs_to :activity
  belongs_to :identity

  accepts_nested_attributes_for :activity

  attr_accessor :publish_on
end

app/models/mention.rb
class Mention < Socialization::ActiveRecordStores::Mention
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  mount_uploader :name, ImageUploader
  belongs_to :activity
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :activity
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user

  mount_uploader :avatar, AvatarUploader

  validates_date :date_of_birth

end

app/models/user.rb
class User < ActiveRecord::Base

  extend FriendlyId

  has_many :identities
  has_many :activities
  has_one :profile, dependent: :destroy
  accepts_nested_attributes_for :profile, allow_destroy: true

  acts_as_followable
  acts_as_follower

  acts_as_messageable

  TEMP_EMAIL_PREFIX = 'dummy@mail'
  TEMP_EMAIL_REGEX = /\Adummy@mail/

  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :omniauthable

  friendly_id :slug_candidates, use: :slugged

  validates_presence_of :name
  validates :email, presence: true, uniqueness: true, format: { without: TEMP_EMAIL_REGEX, on: :update }
  with_options :if => :password_required? do |v|
    v.validates_presence_of     :password
    v.validates_confirmation_of :password
    v.validates_length_of       :password, :within => Devise.password_length, :allow_blank => true
  end

  attr_accessor :status

  class << self

    def find_for_oauth(auth, signed_in_resource = nil)
      identity = Identity.find_for_oauth(auth)
      user = signed_in_resource ? signed_in_resource : identity.user
      if user.nil?
        email_is_verified = auth.info.email && (auth.info.verified || auth.info.verified_email)
        email = auth.info.email if email_is_verified
        user = User.where(:email => email).first if email
        if user.nil?
          user = User.new(
            name: auth.extra.raw_info.name,
            email: email ? email : "#{TEMP_EMAIL_PREFIX}-#{auth.uid}-#{auth.provider}.com",
            password: Devise.friendly_token[0,20]
          )
          user.skip_confirmation!
          user.save!
        end
      end
      if identity.user != user
        identity.user = user
        identity.save!
      end
      user
    end

    def search params
      if params.is_a? Array
        where(id: 0)
      else
        where('lower(name) like ?', "%#{params.to_s.downcase}%")
      end
    end

  end

  #friendly slug candidates
  def slug_candidates
    [
      :name,
      [:name, :id]
    ]
  end

  #mailboxer methods
  def mailboxer_email object
    email
  end

  def mailboxer_name
    name
  end

  #activities
  def recent_activities search = nil, page=nil,per=10
    activities.where('lower(title) like ?', "%#{search}%").order('updated_at desc').page(page).per(per) + followees_recent_activities(page,per)
  end

  def followees_recent_activities search=nil, page=nil,per=10
    Activity.where(user_id: followees(self.class).map(&:id)<<self.id).where('lower(title) like ?', "%#{search}%").order('updated_at desc').order('updated_at desc').page(page).per(per)
  end

  protected

  # From devise
  def password_required?
    !persisted? || !password.nil? || !password_confirmation.nil?
  end

  def email_verified?
    self.email && self.email !~ TEMP_EMAIL_REGEX
  end

end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def new_activity_manifest activity
    activity.manifests.build
  end

  def alert_class level
    style = 'default'
    case level
      when :notice
        style = 'info'
      when :error
        style = 'danger'
      when :alert
        style = 'warning'
      when :success
        style = 'success'
    end
    style
  end

  def avatar user=nil
    if profile user
      return profile(user).avatar.blank? ? default_avatar : profile(user).avatar
    end
    default_avatar
  end

  def profile user = nil
    user.nil? ? current_user.profile : user.profile
  end

  def default_avatar
    'avatar-default.png'
  end

  def search_route route = nil
    if route.nil?
      case params[:controller]
        when 'profile' then people_path
        when 'activities' then activities_path
        else route
      end
    end
    route
  end

  def activity_attachment activity

  end

  def authored_by user
    user.id.eql?(current_user.id) ? 'you' : link_to(user.name, '#')
  end

end

app/helpers/base_helper.rb
module BaseHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper

  def unread_messages_count
    mailbox.inbox(:unread => true).count(:id, :distinct => true)
  end

  def active_folder folder
    "active" if params[:action].eql? folder
  end

end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shareworld</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<div class="container-fluid">
		<%= render 'shared/navigation' %>
		<%= render 'shared/flash' %>
		<%= yield %>
	</div>

	 <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
   <%= yield :script %>
</body>
</html>

app/views/layouts/session.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shareworld</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="container-fluid">
    <%= render 'shared/flash' %>
    <%= yield %>
  </div>

   <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>

app/views/shared/_errors_explanation.html.erb
<% if errors.any? %>
  <div class="alert alert-danger">
    <ul>
      <% errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<div id="flash-message" class="row">
<% [:notice, :error, :alert, :success].each do |level| %>
  <% unless flash[level].blank? %>
    <div class="alert alert-<%= alert_class(level) %> flash-message">
    <button type='button' class='close' data-dismiss='alert'>
      <i class='icon-remove'></i>
    </button>
    <center>
      <strong><%=flash[level]%></strong>
    </center>
  </div>
  <% end %>
<% end %>
</div>

app/views/shared/_form_search.html.erb
<%= form_tag search_route, method: 'get', class: 'navbar-form navbar-left', role: 'search' do  %>
  <div class="form-group">
    <%= text_field_tag :search, params[:search], class: 'form-control', placeholder: 'search' %>
  </div>
  <button type="submit" class="btn btn-default">Search</button>
<% end %>

app/views/shared/_navigation.html.erb
<div class="row">
	<div class="col-md-12">
		<nav class="navbar navbar-default navbar" role="navigation">
			<div class="navbar-header">

				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
					 <span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
				</button> <a class="navbar-brand" href="#">Open World</a>
			</div>

			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
				<ul class="nav navbar-nav">
					<li>
						<%= link_to 'Dashboard', root_path %>
					</li>
					<li>
						<%= link_to 'People', people_path %>
					</li>
				</ul>

				<%= render partial: 'shared/form_search' %>

				<ul class="nav navbar-nav navbar-right">
					<li>
						<li>
							<%= link_to "Inbox <span class='label label-danger pull-right'>#{unread_messages_count}</span>".html_safe, messages_inbox_path %>
						</li>
					</li>
					<li>
						<li class="dropdown">
							 <a href="#" class="dropdown-toggle" data-toggle="dropdown">Menu<strong class="caret"></strong></a>
							<ul class="dropdown-menu">
								<li>
									<%= link_to "<i class='icon icon-user'></i> Profile".html_safe, profile_path %>
								</li>
								<li>
									<%= link_to "<i class='icon icon-lock'></i> Change Password".html_safe, edit_password_profile_path %>
								</li>
								<li class="divider">
								</li>
								<li>
									<%= link_to 'Logout', destroy_user_session_path, method: :delete %>
								</li>
							</ul>
						</li>
					</li>
				</ul>
			</div>

		</nav>
	</div>
</div>

app/views/shared/_no_query_found.html.erb
<div class="col-md-12">
  <div class="alert alert-dismissable alert-warning">

    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
      ×
    </button>
    <div class="center-text">
         <strong>No query found.</strong>
    </div>
  </div>
</div>