config/routes.rb
Rails.application.routes.draw do

  devise_for :users,
    path: '',
    path_names: {sign_in: 'login', sign_out: 'logout'},
    controllers: { omniauth_callbacks: 'omniauth_callbacks' }

   root 'dashboards#index'

  resources :dashboards, only: [:index]

  get 'profile', to: 'profiles#show', as: :profile
  get 'profile/edit', to: 'profiles#edit', as: :edit_profile
  put 'profile', to: 'profiles#update'
  get 'profile/edit_password', to: 'profiles#edit_password', as: :edit_password_profile

  resources :activities

  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  get "messages/inbox" => "messages#inbox", as: :messages_inbox
  get "messages/sent" => "messages#sent", as: :messages_sent
  get "messages/trash" => "messages#trash", as: :messages_trash

  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

  resources :people, only: [:index, :show] do
    member do
      post :follow
      post :unfollow
    end
  end

end

app/models/activity.rb
class Activity < ActiveRecord::Base

  extend FriendlyId

  belongs_to :user
  has_one :link
  has_one :photo
  has_one :post
  has_many :manifests
  has_many :identities, through: :manifests
  accepts_nested_attributes_for :manifests

  friendly_id :title, :use => :slugged

  validates_presence_of :title

  before_save :content

  attr_accessor :image, :image_description, :video, :video_description, :status

  validate :share

  class << self
  end

  def create_activity
    manifests.each do |manifest| manifests.delete(manifest) unless manifest.publish_on end
    save
  end

  def image?
    image.instance_of? ActionDispatch::Http::UploadedFile
  end

  def link?
    /(https?:\/\/)?\w*\.\w+(\.\w+)*(\/\w+)*(\.\w*)?/.match(title)
  end

  def content
    begin
      if image?
        build_photo name: image
      elsif link?
        url = link?.to_s
        build_link(url: url)
      else
        build_post content: title
      end
    rescue e
      return false
    end
  end

  def share

  end

end

app/controllers/activities_controller.rb
class ActivitiesController < BaseController

  @@friendly_id = true

  before_filter :activity, only: [:create]
  respond_to :js

  def index

  end

  def show

  end

  def create
    @resource.create_activity
    redirect_to root_path, notice: 'Post submitted'
  end

  def update

  end

  protected

  private

  def activity
    @resource.user = current_user
  end

  def activity_params
    params.require(:activity).permit(:title, :image, manifests_attributes: [:identity_id, :publish_on])
  end

end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/_activities.html.erb
<div class="activities">

  <%= render 'shared/no_query_found' if recents_activities.blank? %>

  <% recents_activities.each do |activity| %>
    <% if activity.persisted? %>
      <div id="postlist">
        <div class="panel">

          <div class="panel-body">

            <%= activity_attachment activity %>

            <article>
              <%= activity.title %>
              ...<%= link_to 'Read more', activity_path(activity) %>
            </article>
            <small>
              <%= time_ago_in_words activity.updated_at %> ago
            </small>
          </div>

          <div class="panel-footer">
                <small>
                  <%= link_to 'like', '#' %>
                  <%= link_to 'comment', '#' %>
                  <span class='pull-right'>
                    <%= authored_by activity.user %>
                  </span>
                </small>
          </div>

        </div>
      </div>
    <% end %>
  <% end %>
  <div class="text-center"><a href="#" id="loadmore" class="btn btn-primary">Older Activities...</a></div>
</div>

app/views/activities/_form.html.erb
<article>
  <%= form_for activity, html: {multipart: true}, remote: false do |f| %>
    <%= hidden_field_tag :authenticity_token, form_authenticity_token -%>
    <%= f.hidden_field :user_id %>

    <%= f.text_area :title, rows: 5, cols: 50, placeholder: 'Share your thoughts here!' %>

    <section class="preview"></section>

    <section class="wall_input-actions">
    <%= f.file_field :image %>
    <%= f.submit 'Post', class: "btn" %>

    <% current_user.identities.each do |identity| %>
      <% f.fields_for new_activity_manifest(f.object) do |m| %>
        <%= m.hidden_field :identity_id %>
        <div class="checkbox">
          <label>
            <%= m.check_box :publish_on, {}, true %>
            <%= identity.provider %>
          </label>
        </div>
        <% end %>
      <% end %>
    </section>
  <%end%>
</article>